-- Flyway Migration V4: Fix auto-increment identity column counters for H2 & PostgreSQL

ALTER TABLE users ALTER COLUMN id RESTART WITH 100;
ALTER TABLE customers ALTER COLUMN id RESTART WITH 100;
ALTER TABLE sites ALTER COLUMN id RESTART WITH 100;
ALTER TABLE work_orders ALTER COLUMN id RESTART WITH 100;
ALTER TABLE parts ALTER COLUMN id RESTART WITH 100;
ALTER TABLE attachments ALTER COLUMN id RESTART WITH 100;
ALTER TABLE notifications ALTER COLUMN id RESTART WITH 100;
ALTER TABLE work_order_status_history ALTER COLUMN id RESTART WITH 100;
ALTER TABLE part_usages ALTER COLUMN id RESTART WITH 100;
ALTER TABLE time_logs ALTER COLUMN id RESTART WITH 100;

ALTER SEQUENCE IF EXISTS users_id_seq RESTART WITH 100;
ALTER SEQUENCE IF EXISTS customers_id_seq RESTART WITH 100;
ALTER SEQUENCE IF EXISTS sites_id_seq RESTART WITH 100;
ALTER SEQUENCE IF EXISTS work_orders_id_seq RESTART WITH 100;
ALTER SEQUENCE IF EXISTS parts_id_seq RESTART WITH 100;
ALTER SEQUENCE IF EXISTS attachments_id_seq RESTART WITH 100;
ALTER SEQUENCE IF EXISTS notifications_id_seq RESTART WITH 100;
ALTER SEQUENCE IF EXISTS work_order_status_history_id_seq RESTART WITH 100;
ALTER SEQUENCE IF EXISTS part_usages_id_seq RESTART WITH 100;
ALTER SEQUENCE IF EXISTS time_logs_id_seq RESTART WITH 100;
